server:
  port: 8201
spring:
  data:
    elasticsearch:
      cluster-name: elasticsearch # 节点名字 默认elasticsearch
      cluster-nodes: 192.168.70.128:9300 # 节点地址 多个节点用逗号隔开
      repositories:
        enabled: true
  datasource:
    druid:
      stardust:
        url: jdbc:mysql://localhost:3306/stardust?characterEncoding=utf-8
        username: root
        password:
        driverClassName: com.mysql.jdbc.Driver
        type: com.alibaba.druid.pool.DruidDataSource
        filters: stat
      stardust-spider:
        url: jdbc:mysql://localhost:3306/stardust_spider?characterEncoding=utf-8
        username: root
        password:
        driverClassName: com.mysql.jdbc.Driver
        type: com.alibaba.druid.pool.DruidDataSource
        filters: stat
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8101/eureka/
