spring:
  application:
    name: RouterGateway
zuul:
  routes:
    api-a:
      path: /es/**
      serviceId: Elasticsearch
    api-b:
      path: /api-b/**
      serviceId: ServiceFeign
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8101/eureka/
server:
  port: 8103
