server:
  port: 8130
spring:
  application:
    name: manager
  profiles:
    active: local
  datasource:
    hikari:
      magic:
        jdbc-url: jdbc:mysql://localhost:3306/magic?characterEncoding=utf-8&serverTimezone=GMT&autoReconnect=true
        username: root
        password: stardust
        driver-class-name: com.mysql.cj.jdbc.Driver
  redis:
    host: localhost
    port: 6379
    password: stardust
    pool:
      max-active: 8
      max-wait: 2
      max-idle: 8
      min-idle: 0
  data:
    elasticsearch:
      cluster-name: elasticsearch
      cluster-nodes: 192.168.70.128:9300
      repositories:
        enabled: true
mybatis:
  configuration:
    map-underscore-to-camel-case: true
fdfs:
  connect-timeout: 6000
  so-timeout: 15000
  thumbImage:
    width: 150
    height: 150
  tracker-list: 47.106.98.71:22122
  storage-url: http://47.106.98.71:8888
