server:
  port: 8130
spring:
  application:
    name: manager
  profiles:
    active: local
  datasource:
    hikari:
      maximum-pool-size: 3
      magic:
        jdbc-url: jdbc:mysql://localhost:3306/magic?characterEncoding=utf-8&serverTimezone=GMT&autoReconnect=true
        username: root
        password: stardust
        driver-class-name: com.mysql.cj.jdbc.Driver
  data:
    elasticsearch:
      cluster-name: elasticsearch
      cluster-nodes: 192.168.70.128:9300
      repositories:
        enabled: true
mybatis:
  configuration:
    map-underscore-to-camel-case: true
