server:
  port: 8240
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8101/eureka/
spring:
  application:
    name: cache
  profiles:
    active: local
  redis:
    host: 192.168.70.128
    port: 6379
    password: stardust
feign:
  hystrix:
    enabled: true
  httpclient:
    enabled: true
hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 50000
