server:
  port: 8280
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8101/eureka/
spring:
  application:
    name: demo
  profiles:
    active: local
  redis:
    host: 192.168.70.128
    port: 6379
    password: stardust
  datasource:
    hikari:
      magic:
        jdbc-url: jdbc:mysql://localhost:3306/magic?characterEncoding=utf-8&serverTimezone=GMT
        username: root
        password:
        driver-class-name: com.mysql.jdbc.Driver
  data:
    elasticsearch:
      cluster-name: elasticsearch
      cluster-nodes: 192.168.70.128:9300
      repositories:
        enabled: true
mybatis:
  configuration:
    map-underscore-to-camel-case: true
feign:
  hystrix:
    enabled: true
  httpclient:
    enabled: true
hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 50000
fdfs:
  connect-timeout: 600
  so-timeout: 1500
  thumbImage:
    width: 150
    height: 150
  tracker-list: 192.168.70.131:22122
  storage-url: http://192.168.70.131:8888
