spring:
  application:
    name: gateway
zuul:
  routes:
    api-a:
      path: /security/**
      serviceId: security
    api-b:
      path: /api-b/**
      serviceId: ServiceFeign
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8101/eureka/
server:
  port: 8103
