server:
  port: 9000
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8101/eureka/
spring:
  application:
    name: manager
  profiles:
    active: local
  redis:
    host: 192.168.70.128
    port: 6379
    password: stardust
    pool:
      max-active: 8
      max-wait: 2
      max-idle: 8
      min-idle: 0
feign:
  hystrix:
    enabled: true
  httpclient:
    enabled: true
hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 50000
