server:
  port: 8200
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8101/eureka/
spring:
  application:
    name: providergateway
  profiles:
    active: local
  gateway:
    discovery:
      locator:
        enabled:true
        lowerCaseServiceId:true
feign:
  hystrix:
    enable: true
